### ISSUE TITLE
加载失败，请检查网络连接

### ISSUE THREAD

**Issue by beilunyang** [songxiaoliang/visitor-flutter#1]
环境: 乐视Pro3/Android6.0.1
1. 扫码安装体验包，打开提示加载失败，请检查网络连接
2. 用`Charles`抓包，发现没有任何请求发送

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by songxiaoliang** [comment]
@beilunyang  刚刚由于服务器问题，现在已恢复。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
