### ISSUE TITLE
服务端 API 接口报 404

### ISSUE THREAD

**Issue by gdut-yy** [songxiaoliang/visitor-flutter#12]
https://dd.shmy.tech/api/client/classification/

https://dd.shmy.tech/api/client/video/

以上 API 接口报 404，答辩在即，求修复，或告知替代方法，毕业设计用到了该接口，万分感谢！！

**Comment by songxiaoliang** [comment]
@gdut-yy 该接口是引用的第三方，所以目前我无法去做修复。建议是去聚合上看下，然后拿到数据，自己mock

**Comment by gdut-yy** [comment]
已与官方联系，黑人视频APP(安卓版)将于5月12日24:00进行关闭进入维护状态，相关API接口进行维护。可使用网页版API替代（需要自行 merge）。

本人已改用豆瓣开放平台 API 进行 merge。感谢你的回复！！
