### ISSUE TITLE
void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener

### ISSUE THREAD

**Issue by LeoAiolia** [songxiaoliang/visitor-flutter#15]
Compiler message:
file:///Users/dev-yxr/flutter/.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-0.5.1/lib/cached_network_image.dart:199:38: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/dev-yxr/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/dev-yxr/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      oldImageStream?.removeListener(_handleImageChanged);
                                     ^
file:///Users/dev-yxr/flutter/.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-0.5.1/lib/cached_network_image.dart:200:32: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/dev-yxr/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/dev-yxr/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      _imageStream.addListener(_handleImageChanged);
                               ^
file:///Users/dev-yxr/flutter/.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-0.5.1/lib/cached_network_image.dart:210:34: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/dev-yxr/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/dev-yxr/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    _imageStream?.removeListener(_handleImageChanged);
                                 ^
file:///Users/dev-yxr/flutter/.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-0.5.1/lib/cached_network_image.dart:465:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/dev-yxr/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on /Users/dev-yxr/Documents/GitHub/visitor-flutter/lib/main.dart
Error launching application on iPhone Xʀ.

**Comment by amfangYahoo** [comment]
I tested, this should be version imcompatible issue， I upgrade Flutter to latest version, then there has this issue.
I fixed this to use cached_network_image: ^1.0.0, and update all to compatible the latest Flutter. Then can pass this issue.

Also change cachedNetworkImage to below in components/cached_image_component.dart as below:

    return CachedNetworkImage(
        imageUrl: imageUrl.startsWith("http://") ? imageUrl.replaceFirst("http://", "https://") : imageUrl,
        placeholder: (context, url) => CircularProgressIndicator(),
        errorWidget: (context, url, error) => Icon(Icons.error),
        fit:BoxFit.cover,
    );
