### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.openeyeflutter-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.openeyeflutter-2/lib/arm, /data/app/com.example.openeyeflutter-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by jp1017** [songxiaoliang/visitor-flutter#3]
重新编译的项目，解压apk发现，确实没有libflutter.so文件，咋回事？

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by songxiaoliang** [comment]
@jp1017 什么机型


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by wangjinbiao1985** [comment]
大神好，先给你个star！
我下载源码后，用as编译，手机通过usb连接电脑真机调试，华为荣耀v10 android 9.0系统上每次启动闪退！后来找了款华为旧手机，android 6.0系统，运行正常！
但是我扫描你给的二维码下载的apk在华为荣耀v10 android 9.0系统运行是完美的！
求解！

**Comment by songxiaoliang** [comment]
这个问题是由于 gradle文件的ndk配置导致，如下： {
abiFilters "armeabi-v7a", "x86"
}
该问题已修复，可见最新代码。
