### ISSUE TITLE
闪退求助！

### ISSUE THREAD

**Issue by jessen1985** [songxiaoliang/visitor-flutter#4]
大神好，先给你个star！
我下载源码后，用as编译，手机通过usb连接电脑真机调试，华为荣耀v10 android 9.0系统上每次启动闪退！后来找了款华为旧手机，android 6.0系统，运行正常！
但是我扫描你给的二维码下载的apk在华为荣耀v10 android 9.0系统运行是完美的！
求解！

**Comment by songxiaoliang** [comment]
@wangjinbiao1985 用vscode打包试下


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by jessen1985** [comment]
我把代码里的        
ndk {
            abiFilters "armeabi-v7a", "x86"
        }
改成
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
然后在
华为v10 android 9.0系统上就ok了。
谢谢。
